#!/usr/bin/env bash
case $1 in
  up )
    pulseaudio-ctl up
    pkill --signal SIGRTMIN+12 i3blocks
    ;;
  down )
    pulseaudio-ctl down
    pkill --signal SIGRTMIN+12 i3blocks
    ;;
  mute )
    pulseaudio-ctl mute
    pkill --signal SIGRTMIN+12 i3blocks
    ;;
esac
